### ISSUE TITLE
The problem with launching and testing the project from Russia

### ISSUE THREAD

**Issue by Andredron** [cjyaddone/ChatWaifuL2D#1]
Unfortunately, due to political restrictions imposed by OpenAI on users from Russia, these users can not test your program, because the registration must enter a phone number.  I have no ideas myself, but for now you can indicate in the documentation that there are restrictions for users from Russia.

**Comment by blackpancake** [comment]
> 

actually there's also restrictions in China
maybe you can rent a phone number of India or Brazil for a while to receive the verification code
some websites provide this kind of service

**Comment by kevl0317** [comment]
> > 
> 
> actually there's also restrictions in China maybe you can rent a phone number of India or Brazil for a while to receive the verification code some websites provide this kind of service

I do agree with this, try renting a phone number or buying an account. That might help.
